// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVguBrPhtdaynZgLncnyOxb6zIma5sCPo',
    appId: '1:703788472351:web:763f39a4bd95e7326f5d2a',
    messagingSenderId: '703788472351',
    projectId: 'mopizza-3184b',
    authDomain: 'mopizza-3184b.firebaseapp.com',
    storageBucket: 'mopizza-3184b.appspot.com',
    measurementId: 'G-KFPLD70D4W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv4lr7GnxJu2_4L04J6WhvAgsiX5DbwBw',
    appId: '1:703788472351:android:f2844f6f6a99b19b6f5d2a',
    messagingSenderId: '703788472351',
    projectId: 'mopizza-3184b',
    storageBucket: 'mopizza-3184b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOmTj1_BnZ3EG-IF5y3iTuaaDwTSeIGyw',
    appId: '1:703788472351:ios:7d2b38fef83b0d386f5d2a',
    messagingSenderId: '703788472351',
    projectId: 'mopizza-3184b',
    storageBucket: 'mopizza-3184b.appspot.com',
    iosBundleId: 'com.delivery.mopizza',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOmTj1_BnZ3EG-IF5y3iTuaaDwTSeIGyw',
    appId: '1:703788472351:ios:7d2b38fef83b0d386f5d2a',
    messagingSenderId: '703788472351',
    projectId: 'mopizza-3184b',
    storageBucket: 'mopizza-3184b.appspot.com',
    iosBundleId: 'com.delivery.mopizza',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVguBrPhtdaynZgLncnyOxb6zIma5sCPo',
    appId: '1:703788472351:web:2f030ab4cc629c206f5d2a',
    messagingSenderId: '703788472351',
    projectId: 'mopizza-3184b',
    authDomain: 'mopizza-3184b.firebaseapp.com',
    storageBucket: 'mopizza-3184b.appspot.com',
    measurementId: 'G-G2RH9M2M6L',
  );
}
